{{- if .Values.gubernator.serviceAccount.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gubernator.fullname" . }}
  labels:
  {{- include "gubernator.labels" . | nindent 4 }}
  annotations:
  {{- include "gubernator.annotations" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gubernator.fullname" . }}
  labels:
  {{- include "gubernator.labels" . | nindent 4 }}
  annotations:
  {{- include "gubernator.annotations" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gubernator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "gubernator.fullname" . }}
{{- end }}