version: '3'
services:
  gubernator-1:
    image: mkbond/gubernator:latest
    command: "/gubernator"
    environment:
      # The address GRPC requests will listen on
      - GUBER_GRPC_ADDRESS=0.0.0.0:81
      # The address HTTP requests will listen on
      - GUBER_HTTP_ADDRESS=0.0.0.0:80
      # Max size of the cache; The cache size will never grow beyond this size.
      - GUBER_CACHE_SIZE=50000
      # A comma separated list of known gubernator nodes
      - GUBER_MEMBERLIST_KNOWN_NODES=gubernator-1,gubernator-2,gubernator-3,gubernator-4
      - GUBER_DATA_CENTER=us-east-1
    ports:
      - "8081:81"
      - "8080:80"

  gubernator-2:
    image: mkbond/gubernator:latest
    command: "/gubernator"
    environment:
      # The address GRPC requests will listen on
      - GUBER_GRPC_ADDRESS=0.0.0.0:81
      # The address HTTP requests will listen on
      - GUBER_HTTP_ADDRESS=0.0.0.0:80
      # Max size of the cache; The cache size will never grow beyond this size.
      - GUBER_CACHE_SIZE=50000
      # A comma separated list of known gubernator nodes
      - GUBER_MEMBERLIST_KNOWN_NODES=gubernator-1,gubernator-2,gubernator-3,gubernator-4
      - GUBER_DATA_CENTER=us-east-1
    ports:
      - "8181:81"
      - "8180:80"

  gubernator-3:
    image: mkbond/gubernator:latest
    command: "/gubernator"
    environment:
      # The address GRPC requests will listen on
      - GUBER_GRPC_ADDRESS=0.0.0.0:81
      # The address HTTP requests will listen on
      - GUBER_HTTP_ADDRESS=0.0.0.0:80
      # Max size of the cache; The cache size will never grow beyond this size.
      - GUBER_CACHE_SIZE=50000
      # A comma separated list of known gubernator nodes
      - GUBER_MEMBERLIST_KNOWN_NODES=gubernator-1,gubernator-2,gubernator-3,gubernator-4
      - GUBER_DATA_CENTER=us-west-2
    ports:
      - "8281:81"
      - "8280:80"

  gubernator-4:
    image: mkbond/gubernator:latest
    command: "/gubernator"
    environment:
      # The address GRPC requests will listen on
      - GUBER_GRPC_ADDRESS=0.0.0.0:81
      # The address HTTP requests will listen on
      - GUBER_HTTP_ADDRESS=0.0.0.0:80
      # Max size of the cache; The cache size will never grow beyond this size.
      - GUBER_CACHE_SIZE=50000
      # A Comma separate list of known gubernator nodes
      - GUBER_MEMBERLIST_KNOWN_NODES=gubernator-1,gubernator-2,gubernator-3,gubernator-4
      - GUBER_DATA_CENTER=us-west-2
    ports:
      - "8381:81"
      - "8380:80"
